### ISSUE TITLE
As a game-player, I want to know how many people have joined the game, so I should see a list of all of the players usernames displayed before the game officially starts. A message will pop up on my screen telling me I have successfully joined the game.

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#1]
As a game-player, I want to know how many people have joined the game, so I should see a list of all of the players usernames displayed before the game officially starts. A message will pop up on my screen telling me I have successfully joined the game.

Acceptance tests:
1. Start new game
2. Join a game
3. Look at list of players for my username

**Comment by Amhepel** [comment]
User story 1: As a game-player, I want to know how many people have joined the game.
Acceptance test 1: A list of all of the players usernames will be displayed before the game officially starts. A message will pop up on my screen telling me I have successfully joined the game.
