### ISSUE TITLE
Civilian task messages

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#2]
As a game-player “civilian”, I want to receive a message with my new objective or instruction at the start of each round, so
at the start of each round, I see a message displayed on my screen with a new objective or instruction.

Acceptance tests:
1. Open anyconnect and connect to vpn.buffalo.edu
2. open up terminal
3. ssh into cheshire (when connected into a UB network)
4. navigate to the directory /CSE442-542/2020-Fall/cse-442g/
5. run server using command "python server.py" in that terminal
6. On your main computer, open up another terminal and navigate to directory where the project is on your local machine.
7. Once in that directory, run "python Main.py"
8. Start new game
9. At start of new level a prompt message should be displayed

**Comment by Amhepel** [comment]
User story 2: As a game-player “civilian”, I want to receive a message with my new objective or instruction at the start of each round.
Acceptance test 2: At the start of each round, I see a message displayed on my screen with a new objective or instruction.
