### ISSUE TITLE
As a gameplayer I want to be able to move my character, so when I press W,A,S, or D keys I should see my character move in a corresponding direction.

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#3]
As a gameplayer I want to be able to move my character, so when I press W,A,S, or D keys I should see my character move in a corresponding direction.

Acceptance test:
1. Start new game
2. Press the movement key
3. Character on screen should move around

**Comment by Amhepel** [comment]
User story 3: As a game-player I want to control my character’s movement with WASD to move around the map when the game is going on, in real time. 
Acceptance test 3: When I press a W,A,S, or D key I see a change in value in the movement variable or in memory. I see your character move on the screen in the direction I pressed (Up W, Left A, Down S, Right D). Other game players watch my character move in the intended direction on their screen in real time.

**Comment by Amhepel** [comment]
Duplicate task
