### ISSUE TITLE
As a game-player, I want there to be an impostor randomly selected at the beginning of each game, so at the start of the game a random gameplayer should be assigned as the imposter, and I should see a message on the screen stating my role as imposter or civilian.

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#4]
As a game-player, I want there to be an impostor randomly selected at the beginning of each game, so at the start of the game a random gameplayer should be assigned as the imposter, and I should see a message on the screen stating my role as imposter or civilian.

Acceptance test:
1. Open and enter new game
2. Start new game
3. One of the players should see their role as imposter.

**Comment by Amhepel** [comment]
User story 4: As a game-player, I want there to be an impostor randomly selected at the beginning of each game.
Acceptance test 4: Only 1 of the players will get a message notifying them they are the impostor at the beginning of the round. A variable showing the identity of each gameplayer (civilian or imposter) will be assigned and seen using a print statement for output in the back end.

**Comment by Amhepel** [comment]
Similar to a task already assigned.
