### ISSUE TITLE
As a game-player “impostor”, I want a kill option to appear on screen when in the set proximity of another player, so when I am within the set range of another player, a button will appear on screen with an option to kill this player while they are still within this range.

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#5]
As a game-player “impostor”, I want a kill option to appear on screen when in the set proximity of another player, so when I am within the set range of another player, a button will appear on screen with an option to kill this player while they are still within this range.

Acceptance tests:
1. Start new game as imposter
2. Get within range of another player
3. Click a kill button
4. Watch that player's character die

**Comment by Amhepel** [comment]
User story 5: As a game-player “impostor”, I want a kill option to appear on screen when in the set proximity of another player.
Acceptance test 5: When the player designated as impostor is within the set range of another player, a button will appear on screen with an option to kill this player while they are still within this range.
