### ISSUE TITLE
As a game-player, I want to win the game as an impostor by killing all players (except for 1), or winning as a civilian by voting off the impostor, so a win message should be displayed when a win state has occurred.

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#6]
As a game-player, I want to win the game as an impostor by killing all players (except for 1), or winning as a civilian by voting off the impostor, so a win message should be displayed when a win state has occurred.

Acceptance tests:
1. Start new game
2. If I'm an imposter kill off every other player except one other player
3. If I'm a civilian, vote off the imposter
4. I should see a win message showing if the imposter or the civilians won the game

**Comment by Amhepel** [comment]
User story 6: As a game-player, I want to win the game as an impostor by killing all players (except for 1), or winning as a civilian by voting off the impostor.
Acceptance test 6: When voting off the impostor the game will end and there will be a victory message for civilians, and a defeat message for impostors. While if you kill all but the last civilians as impostor, you will see a victory message, and a defeat message for civilians.

**Comment by Amhepel** [comment]
Similar to task already assigned.
