### ISSUE TITLE
Character visibility

### ISSUE THREAD

**Issue by cheesynoz** [UB-CSE/course-project-a5-ezpz#7]
Make the player visible on the screen

Acceptance Test:
1) When a user open the application they will be prompted to select online. 
2) When online is selected, a new Window will pop up, with a character and a background, the user should be able to see their character.

**Comment by Amhepel** [comment]
User story 7: As a game-player, when you are killed, or voted off, your in game character will no longer exist. 
Acceptance test 7: The game-player will no longer have their character visible on screen and their character will disappear from the other players screens as well. I will see a message saying that I have died.
